export const Barrios: { value: string; label: string }[] = [
  { value: "cualquiera", label: "Cualquiera" },
  { value: "anaconda", label: "Anaconda" },
  { value: "antoniopolis", label: "Antoniópolis" },
  { value: "arachania", label: "Arachania" },
  { value: "atlantica", label: "Atlántica" },
  { value: "barrio-country", label: "Barrio Country" },
  { value: "barrio-parque", label: "Barrio Parque" },
  { value: "cerro-aspero-garzon", label: "Cerro Aspero Garzon" },
  { value: "costa-azul", label: "Costa Azul" },
  { value: "la-aguada", label: "La Aguada" },
  { value: "la-paloma", label: "La Paloma" },
  { value: "la-pedrera", label: "La Pedrera" },
  { value: "oceania-del-polonio", label: "Oceanía del Polonio" },
  { value: "playa-serena", label: "Playa Serena" },
  { value: "pueblo-nuevo", label: "Pueblo Nuevo" },
  { value: "punta-rubia", label: "Punta Rubia" },
  { value: "rocha", label: "Rocha" },
  { value: "san-antonio", label: "San Antonio" },
  {
    value: "san-sebastian-de-la-pedrera",
    label: "San Sebastián de La Pedrera",
  },
  { value: "santa-isabel", label: "Santa Isabel" },
  { value: "sierra-de-rocha", label: "Sierra de Rocha" },
  {
    value: "no-aplica",
    label: "No aplica",
  },
];

